spring:
  application:
    name: spring-ai-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai_demo
    username: spring_ai_demo
    password: spring_ai_demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  mvc:
    static-path-pattern: /**
    view:
      prefix: /
      suffix: .html
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public
